[tool.autopep8]
max_line_length = 96

ignore = [
    "E302", # not enough blank lines (sometimes useful)
    "E303", # too many blank lines (sometimes useful!)
    "E402", # "module level import not at top of file"
]


[tool.mypy]
python_version = 3.9

mypy_path = "typings"
exclude = "typings.*"

follow-imports = "silent"
ignore_missing_imports = true
namespace_packages = true

strict_optional = true
disallow_subclassing_any = false
disallow_any_generics = true
disallow_untyped_calls = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true


[tool.isort]
# Blender primary before stdlib bits because that seems to be the order
# used in most of the blender built-in addons and such. There's probably
# no reason things *need* to be that way, but a consistently followed
# mediocre standard is better than a poorly followed one.
sections = [
    "FUTURE",
    "BLENDER_PRIMARY",
    "STDLIB",
    "BLENDER_SECONDARY",
    "BLENDER_OTHER",
    "FIRSTPARTY",
    "THIRDPARTY",
    "LOCALFOLDER",
]

known_blender_primary = [ "bpy", "bmesh", "mathutils" ]

known_blender_secondary = [
    "addon_utils",
    "aud",
    "bgl",
    "bl_operators",
    "bl_ui",
    "bl_ui_utils",
    "blend_render_info",
    "blf",
    "bpy_extras",
    "freestyle",
    "gpu",
    "gpu_extras",
    "nodeitems_builtins",
    "nodeitems_utils",
    "rna_keymap_ui",
    "rna_prop_ui",
]

known_blender_other = [
    "animsys_refactor",
    "bl_app_override",
    "bl_app_template_utils",
    "bl_i18n_utils",
    "bl_keymap_utils",
    "bl_previews_utils",
    "bl_rna_utils",
    "bpy_restrict_state",
    "bpy_types",
    "console",
    "console_python",
    "console_shell",
    "graphviz_export",
    "keyingsets_builtins",
    "keyingsets_utils",
    "rna_info",
    "rna_xml",
    "sys_info",
]
